import type { MigrationDefinition } from "./files/context.js";

function quoteIdentifier(identifier: string): string {
  return `"${identifier.replaceAll('"', '""')}"`;
}

export const migration: MigrationDefinition = {
  async up({ context }) {
    const schema = quoteIdentifier(context.schema);
    await context.queryInterface.sequelize.query(
      `CREATE TABLE ${schema}.characters (
         id integer NOT NULL,
         name text NOT NULL,
         status text NOT NULL,
         species text NOT NULL,
         character_type text NOT NULL,
         gender text NOT NULL,
         origin_name text NOT NULL,
         origin_url text NOT NULL,
         image_url text NOT NULL,
         is_favorite boolean NOT NULL DEFAULT false,
         created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
         updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
         CONSTRAINT characters_pkey PRIMARY KEY (id)
       )`,
      { transaction: context.transaction },
    );
    await context.queryInterface.sequelize.query(
      `CREATE TABLE ${schema}.comments (
         id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
         character_id integer NOT NULL,
         body text NOT NULL,
         created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
         updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
         CONSTRAINT comments_pkey PRIMARY KEY (id),
         CONSTRAINT comments_body_length_check
           CHECK (pg_catalog.char_length(body) >= 1 AND pg_catalog.char_length(body) <= 1000),
         CONSTRAINT comments_character_id_fkey
           FOREIGN KEY (character_id) REFERENCES ${schema}.characters(id)
           ON UPDATE RESTRICT ON DELETE RESTRICT
       )`,
      { transaction: context.transaction },
    );
    await context.queryInterface.sequelize.query(
      `CREATE INDEX comments_character_id_idx
         ON ${schema}.comments USING btree (character_id)`,
      { transaction: context.transaction },
    );
  },
  async down({ context }) {
    const schema = quoteIdentifier(context.schema);
    await context.queryInterface.sequelize.query(
      `DROP TABLE ${schema}.comments`,
      { transaction: context.transaction },
    );
    await context.queryInterface.sequelize.query(
      `DROP TABLE ${schema}.characters`,
      { transaction: context.transaction },
    );
  },
};
